version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=API;User Id=sa;Password=YourStrongPassword123!;MultipleActiveResultSets=true;TrustServerCertificate=true
    depends_on:
      - db
    networks:
      - api-network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123!
      - MSSQL_PID=Express
    ports:
      - "1434:1433"  # Usar puerto 1434 ya que 1433 está en uso
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init-db.sql:/init-db.sql
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  sqlserver_data:
